/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreloaderPreviewRouteImport } from './routes/preloader-preview'
import { Route as IndexRouteImport } from './routes/index'

const PreloaderPreviewRoute = PreloaderPreviewRouteImport.update({
  id: '/preloader-preview',
  path: '/preloader-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preloader-preview': typeof PreloaderPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preloader-preview': typeof PreloaderPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preloader-preview': typeof PreloaderPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preloader-preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preloader-preview'
  id: '__root__' | '/' | '/preloader-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreloaderPreviewRoute: typeof PreloaderPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preloader-preview': {
      id: '/preloader-preview'
      path: '/preloader-preview'
      fullPath: '/preloader-preview'
      preLoaderRoute: typeof PreloaderPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreloaderPreviewRoute: PreloaderPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
